
```{r}
rm(list=ls())
library(dplyr)
library(ggplot2)
library(lubridate)
library(tseries)
library(tidyr)
```



```{r}
holidays_events <- read.csv("~/personal/kaggle/store_forecasting/data/holidays_events.csv")
oil <- read.csv("~/personal/kaggle/store_forecasting/data/oil.csv")
sample_submission <- read.csv("~/personal/kaggle/store_forecasting/data/sample_submission.csv")
stores <- read.csv("~/personal/kaggle/store_forecasting/data/stores.csv")
test <- read.csv("~/personal/kaggle/store_forecasting/data/test.csv")
train <- read.csv("~/personal/kaggle/store_forecasting/data/train.csv")
transactions <- read.csv("~/personal/kaggle/store_forecasting/data/transactions.csv")
```

#Cleaning "oil" dataframe
```{r}
colnames(oil) <- c("date", "price")
oil_aug <- oil %>% 
  drop_na(price) %>%
  mutate(market_gap = round(as.numeric(difftime(date, lag(date), unit = "days"))),
                          date = as.Date(date),
                          day_of_week = weekdays(date),
                          price_change = price - lag(price))
oil_aug <- oil_aug %>%
  mutate(month = month(date),
         week = week(date),
         year = year(date),
         day = day(date))
```

#Cleaning "transactions" dataframe






#Cleaning "stores" dataframe


















