---
title: "judge_fixed_effects_IV"
output: html_document
---

```{r}
library(SteinIV)
library(lme4)
library(dplyr)
library(ggplot2)
library(ivreg)
```


```{r}
# Simulation comparison of scenario when JIVE/judge fixed effects methods
# seem problematic

## Assumptions
#
#
#
#

# We draw judges from a Normal distribution with a baseline severity plus
# idiosyncratic sentencing characteristics based on 
# observable characteristics (here, only sex, race, time)

# Sex: 0 = man, 1 = woman
# Race: 0 = White, 1 = Black
# Time: t = 0,1,2,3,4,5

num_judges <- 10
num_people <- 10000

judges_ovr <- rbeta(num_judges, 4, 4)
judges_race <- rbeta(num_judges, 10, 10) - 0.4
judges_sex <- rbeta(num_judges, 20, 20) - 0.5
judges_time <- rbeta(num_judges, 80, 80) - 0.5

judges <- as.data.frame(x = list(judges_ovr, judges_race, judges_sex, judges_time),
                        col.names = list("j_ovr","j_race","j_sex","j_time")) %>%
  mutate(judge_num = row_number())

# Judge true severity function: Severity = Ovr + b1*race + b2*sex + b3*time

race <- rbinom(num_people, 1, 0.1)
sex <- rbinom(num_people, 1, 0.5)
time <-  sample(1:5, num_people, replace=T)
assigned_judge <- sample(1:num_judges, num_people, replace=T)
  
data <- as.data.frame(x = list(race, sex, time, assigned_judge),
                        col.names = list("race","sex","time","assigned_judge")) %>%
  mutate(index = row_number()) %>%
  cross_join(judges, by = c("assigned_judge" = "judge_num")) %>%
  relocate(index) %>%
  mutate(true_severity = pmin(pmax(j_ovr + j_race*race + j_sex*sex + j_time*time, 0), 1))

dgp <- as.data.frame(x = list(race, sex, time, assigned_judge),
                        col.names = list("race","sex","time","assigned_judge")) %>%
  mutate(index = row_number()) %>%
  cross_join(judges) %>%
  relocate(index) %>%
  mutate(true_severity = pmin(pmax(j_ovr + j_race*race + j_sex*sex + j_time*time, 0), 1))
```

```{r}
# Summary stats for judges by severity
judge_severity <- dgp %>%
  filter(assigned_judge == judge_num) %>%
  group_by(assigned_judge, race, sex, time) %>%
  summarize(freq = n(),
            true_severity = mean(true_severity)) %>%
  ungroup()

judge_summ <- judge_severity %>%
  group_by(race, sex, time) %>%
  summarize(num_judges = n(),
    avg_freq = mean(freq),
    min_severity = min(true_severity),
    median_severity = median(true_severity),
    max_severity = max(true_severity),
    std = sd(true_severity))
```


```{r}
realized_data <- dgp %>%
  mutate(sentencing = rbinom(n(),1,true_severity),
         outcome = rbinom(n(),1,0.5 + 0.4*sentencing))
# The true average effect for the compliers is 0.4
```


```{r}
# Calculate the group level means
data2 <- realized_data %>% 
  group_by(judge_num, race, sex, time) %>% 
  mutate(est_severity = combn(sentencing, n()-1, FUN=mean))
```


```{r}
## Model construction

# Model 1: Oracle (2SLS, using true severity)

# Model 2: 2SLS, empirical Bayes

# Model 3: 2SLS, leave-out mean

# Model 4:

```


















